# deploy from root directory with
# "fly deploy -c ./noted/fly.toml --ha=false"

app = "noted-frontend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

primary_region = "mia"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
max_machines_running = 3

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

[build]
dockerfile = "./Dockerfile"

[env]
PORT = "8080"
ENVIRONMENT = "dev"
BACKEND_URL = "https://noted-us4rg.fly.dev"

