// @generated by protoc-gen-es v1.7.2
// @generated from file company.proto (package company.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum company.v1.SubscriptionStatus
 */
export const SubscriptionStatus = proto3.makeEnum(
  "company.v1.SubscriptionStatus",
  [
    {no: 0, name: "UnspecifiedStatus"},
    {no: 1, name: "Active"},
    {no: 2, name: "PastDue"},
    {no: 3, name: "Nonexistent"},
    {no: 4, name: "Cancelled"},
  ],
);

/**
 * @generated from message company.v1.Company
 */
export const Company = proto3.makeMessageType(
  "company.v1.Company",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
    { no: 5, name: "updated_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message company.v1.CompanyBilling
 */
export const CompanyBilling = proto3.makeMessageType(
  "company.v1.CompanyBilling",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "company_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "subscription_status", kind: "enum", T: proto3.getEnumType(SubscriptionStatus) },
    { no: 5, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "billing_start", kind: "message", T: Timestamp, opt: true },
    { no: 7, name: "billing_end", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * @generated from message company.v1.CreateCompanyRequest
 */
export const CreateCompanyRequest = proto3.makeMessageType(
  "company.v1.CreateCompanyRequest",
  () => [
    { no: 1, name: "company_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "customer_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "customer_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "customer_phone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "customer_city", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "customer_line1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "customer_line2", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "customer_postal_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.CreateCompanyResponse
 */
export const CreateCompanyResponse = proto3.makeMessageType(
  "company.v1.CreateCompanyResponse",
  () => [
    { no: 1, name: "company", kind: "message", T: Company },
  ],
);

/**
 * @generated from message company.v1.UpdateCompanyRequest
 */
export const UpdateCompanyRequest = proto3.makeMessageType(
  "company.v1.UpdateCompanyRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.GetCompanyByCodeRequest
 */
export const GetCompanyByCodeRequest = proto3.makeMessageType(
  "company.v1.GetCompanyByCodeRequest",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.GetCompanyByCodeResponse
 */
export const GetCompanyByCodeResponse = proto3.makeMessageType(
  "company.v1.GetCompanyByCodeResponse",
  () => [
    { no: 1, name: "company", kind: "message", T: Company },
  ],
);

/**
 * @generated from message company.v1.GetCompanyByIDRequest
 */
export const GetCompanyByIDRequest = proto3.makeMessageType(
  "company.v1.GetCompanyByIDRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.GetCompanyByIDResponse
 */
export const GetCompanyByIDResponse = proto3.makeMessageType(
  "company.v1.GetCompanyByIDResponse",
  () => [
    { no: 1, name: "company", kind: "message", T: Company },
  ],
);

/**
 * @generated from message company.v1.GetCompanyStatsRequest
 */
export const GetCompanyStatsRequest = proto3.makeMessageType(
  "company.v1.GetCompanyStatsRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message company.v1.GetCompanyStatsResponse
 */
export const GetCompanyStatsResponse = proto3.makeMessageType(
  "company.v1.GetCompanyStatsResponse",
  () => [
    { no: 1, name: "total_notes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "total_notes_this_month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "total_patients", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "total_patients_this_month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "total_nurses", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "total_nurses_this_month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "total_admins", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "total_admins_this_month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message company.v1.GetCompanyBillingRequest
 */
export const GetCompanyBillingRequest = proto3.makeMessageType(
  "company.v1.GetCompanyBillingRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message company.v1.GetCompanyBillingResponse
 */
export const GetCompanyBillingResponse = proto3.makeMessageType(
  "company.v1.GetCompanyBillingResponse",
  () => [
    { no: 1, name: "billing", kind: "message", T: CompanyBilling },
  ],
);

/**
 * @generated from message company.v1.GetEstimatedSubscriptionCostRequest
 */
export const GetEstimatedSubscriptionCostRequest = proto3.makeMessageType(
  "company.v1.GetEstimatedSubscriptionCostRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message company.v1.GetEstimatedSubscriptionCostResponse
 */
export const GetEstimatedSubscriptionCostResponse = proto3.makeMessageType(
  "company.v1.GetEstimatedSubscriptionCostResponse",
  () => [
    { no: 1, name: "estimated_cost", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "total_seats", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "seats_to_remove", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message company.v1.PromoteAdminRequest
 */
export const PromoteAdminRequest = proto3.makeMessageType(
  "company.v1.PromoteAdminRequest",
  () => [
    { no: 1, name: "company_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.DemoteAdminRequest
 */
export const DemoteAdminRequest = proto3.makeMessageType(
  "company.v1.DemoteAdminRequest",
  () => [
    { no: 1, name: "company_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.CreateCheckoutSessionRequest
 */
export const CreateCheckoutSessionRequest = proto3.makeMessageType(
  "company.v1.CreateCheckoutSessionRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message company.v1.CreateCheckoutSessionResponse
 */
export const CreateCheckoutSessionResponse = proto3.makeMessageType(
  "company.v1.CreateCheckoutSessionResponse",
  () => [
    { no: 1, name: "checkout_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message company.v1.CreateBillingPortalSessionRequest
 */
export const CreateBillingPortalSessionRequest = proto3.makeMessageType(
  "company.v1.CreateBillingPortalSessionRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message company.v1.CreateBillingPortalSessionResponse
 */
export const CreateBillingPortalSessionResponse = proto3.makeMessageType(
  "company.v1.CreateBillingPortalSessionResponse",
  () => [
    { no: 1, name: "portal_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

