// @generated by protoc-gen-connect-es v1.4.0
// @generated from file company.proto (package company.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateBillingPortalSessionRequest, CreateBillingPortalSessionResponse, CreateCheckoutSessionRequest, CreateCheckoutSessionResponse, CreateCompanyRequest, CreateCompanyResponse, DemoteAdminRequest, GetCompanyBillingRequest, GetCompanyBillingResponse, GetCompanyByCodeRequest, GetCompanyByCodeResponse, GetCompanyByIDRequest, GetCompanyByIDResponse, GetCompanyStatsRequest, GetCompanyStatsResponse, GetEstimatedSubscriptionCostRequest, GetEstimatedSubscriptionCostResponse, PromoteAdminRequest, UpdateCompanyRequest } from "./company_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service company.v1.CompanyService
 */
export const CompanyService = {
  typeName: "company.v1.CompanyService",
  methods: {
    /**
     * @generated from rpc company.v1.CompanyService.CreateCompany
     */
    createCompany: {
      name: "CreateCompany",
      I: CreateCompanyRequest,
      O: CreateCompanyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.UpdateCompany
     */
    updateCompany: {
      name: "UpdateCompany",
      I: UpdateCompanyRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.GetCompanyByCode
     */
    getCompanyByCode: {
      name: "GetCompanyByCode",
      I: GetCompanyByCodeRequest,
      O: GetCompanyByCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.GetCompanyByID
     */
    getCompanyByID: {
      name: "GetCompanyByID",
      I: GetCompanyByIDRequest,
      O: GetCompanyByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.GetCompanyStats
     */
    getCompanyStats: {
      name: "GetCompanyStats",
      I: GetCompanyStatsRequest,
      O: GetCompanyStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.GetCompanyBilling
     */
    getCompanyBilling: {
      name: "GetCompanyBilling",
      I: GetCompanyBillingRequest,
      O: GetCompanyBillingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.GetEstimatedSubscriptionCost
     */
    getEstimatedSubscriptionCost: {
      name: "GetEstimatedSubscriptionCost",
      I: GetEstimatedSubscriptionCostRequest,
      O: GetEstimatedSubscriptionCostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.PromoteAdmin
     */
    promoteAdmin: {
      name: "PromoteAdmin",
      I: PromoteAdminRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.DemoteAdmin
     */
    demoteAdmin: {
      name: "DemoteAdmin",
      I: DemoteAdminRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.CreateCheckoutSession
     */
    createCheckoutSession: {
      name: "CreateCheckoutSession",
      I: CreateCheckoutSessionRequest,
      O: CreateCheckoutSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc company.v1.CompanyService.CreateBillingPortalSession
     */
    createBillingPortalSession: {
      name: "CreateBillingPortalSession",
      I: CreateBillingPortalSessionRequest,
      O: CreateBillingPortalSessionResponse,
      kind: MethodKind.Unary,
    },
  }
};

