// @generated by protoc-gen-es v1.7.2
// @generated from file company.proto (package company.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Empty, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum company.v1.SubscriptionStatus
 */
export declare enum SubscriptionStatus {
  /**
   * @generated from enum value: UnspecifiedStatus = 0;
   */
  UnspecifiedStatus = 0,

  /**
   * @generated from enum value: Active = 1;
   */
  Active = 1,

  /**
   * @generated from enum value: PastDue = 2;
   */
  PastDue = 2,

  /**
   * @generated from enum value: Nonexistent = 3;
   */
  Nonexistent = 3,

  /**
   * @generated from enum value: Cancelled = 4;
   */
  Cancelled = 4,
}

/**
 * @generated from message company.v1.Company
 */
export declare class Company extends Message<Company> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Company>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.Company";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Company;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Company;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Company;

  static equals(a: Company | PlainMessage<Company> | undefined, b: Company | PlainMessage<Company> | undefined): boolean;
}

/**
 * @generated from message company.v1.CompanyBilling
 */
export declare class CompanyBilling extends Message<CompanyBilling> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string company_id = 2;
   */
  companyId: string;

  /**
   * @generated from field: string customer_id = 3;
   */
  customerId: string;

  /**
   * @generated from field: company.v1.SubscriptionStatus subscription_status = 4;
   */
  subscriptionStatus: SubscriptionStatus;

  /**
   * @generated from field: optional string subscription_id = 5;
   */
  subscriptionId?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp billing_start = 6;
   */
  billingStart?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp billing_end = 7;
   */
  billingEnd?: Timestamp;

  constructor(data?: PartialMessage<CompanyBilling>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CompanyBilling";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompanyBilling;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompanyBilling;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompanyBilling;

  static equals(a: CompanyBilling | PlainMessage<CompanyBilling> | undefined, b: CompanyBilling | PlainMessage<CompanyBilling> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateCompanyRequest
 */
export declare class CreateCompanyRequest extends Message<CreateCompanyRequest> {
  /**
   * @generated from field: string company_name = 1;
   */
  companyName: string;

  /**
   * @generated from field: string customer_email = 2;
   */
  customerEmail: string;

  /**
   * @generated from field: string customer_name = 3;
   */
  customerName: string;

  /**
   * @generated from field: string customer_phone = 4;
   */
  customerPhone: string;

  /**
   * @generated from field: string customer_city = 5;
   */
  customerCity: string;

  /**
   * @generated from field: string customer_line1 = 6;
   */
  customerLine1: string;

  /**
   * @generated from field: optional string customer_line2 = 7;
   */
  customerLine2?: string;

  /**
   * @generated from field: string customer_postal_code = 8;
   */
  customerPostalCode: string;

  /**
   * @generated from field: string token = 9;
   */
  token: string;

  constructor(data?: PartialMessage<CreateCompanyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateCompanyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCompanyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCompanyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCompanyRequest;

  static equals(a: CreateCompanyRequest | PlainMessage<CreateCompanyRequest> | undefined, b: CreateCompanyRequest | PlainMessage<CreateCompanyRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateCompanyResponse
 */
export declare class CreateCompanyResponse extends Message<CreateCompanyResponse> {
  /**
   * @generated from field: company.v1.Company company = 1;
   */
  company?: Company;

  constructor(data?: PartialMessage<CreateCompanyResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateCompanyResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCompanyResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCompanyResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCompanyResponse;

  static equals(a: CreateCompanyResponse | PlainMessage<CreateCompanyResponse> | undefined, b: CreateCompanyResponse | PlainMessage<CreateCompanyResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.UpdateCompanyRequest
 */
export declare class UpdateCompanyRequest extends Message<UpdateCompanyRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string code = 3;
   */
  code?: string;

  /**
   * @generated from field: string token = 4;
   */
  token: string;

  constructor(data?: PartialMessage<UpdateCompanyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.UpdateCompanyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateCompanyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateCompanyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateCompanyRequest;

  static equals(a: UpdateCompanyRequest | PlainMessage<UpdateCompanyRequest> | undefined, b: UpdateCompanyRequest | PlainMessage<UpdateCompanyRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyByCodeRequest
 */
export declare class GetCompanyByCodeRequest extends Message<GetCompanyByCodeRequest> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  constructor(data?: PartialMessage<GetCompanyByCodeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyByCodeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyByCodeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyByCodeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyByCodeRequest;

  static equals(a: GetCompanyByCodeRequest | PlainMessage<GetCompanyByCodeRequest> | undefined, b: GetCompanyByCodeRequest | PlainMessage<GetCompanyByCodeRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyByCodeResponse
 */
export declare class GetCompanyByCodeResponse extends Message<GetCompanyByCodeResponse> {
  /**
   * @generated from field: company.v1.Company company = 1;
   */
  company?: Company;

  constructor(data?: PartialMessage<GetCompanyByCodeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyByCodeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyByCodeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyByCodeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyByCodeResponse;

  static equals(a: GetCompanyByCodeResponse | PlainMessage<GetCompanyByCodeResponse> | undefined, b: GetCompanyByCodeResponse | PlainMessage<GetCompanyByCodeResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyByIDRequest
 */
export declare class GetCompanyByIDRequest extends Message<GetCompanyByIDRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetCompanyByIDRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyByIDRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyByIDRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyByIDRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyByIDRequest;

  static equals(a: GetCompanyByIDRequest | PlainMessage<GetCompanyByIDRequest> | undefined, b: GetCompanyByIDRequest | PlainMessage<GetCompanyByIDRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyByIDResponse
 */
export declare class GetCompanyByIDResponse extends Message<GetCompanyByIDResponse> {
  /**
   * @generated from field: company.v1.Company company = 1;
   */
  company?: Company;

  constructor(data?: PartialMessage<GetCompanyByIDResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyByIDResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyByIDResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyByIDResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyByIDResponse;

  static equals(a: GetCompanyByIDResponse | PlainMessage<GetCompanyByIDResponse> | undefined, b: GetCompanyByIDResponse | PlainMessage<GetCompanyByIDResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyStatsRequest
 */
export declare class GetCompanyStatsRequest extends Message<GetCompanyStatsRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  constructor(data?: PartialMessage<GetCompanyStatsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyStatsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyStatsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyStatsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyStatsRequest;

  static equals(a: GetCompanyStatsRequest | PlainMessage<GetCompanyStatsRequest> | undefined, b: GetCompanyStatsRequest | PlainMessage<GetCompanyStatsRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyStatsResponse
 */
export declare class GetCompanyStatsResponse extends Message<GetCompanyStatsResponse> {
  /**
   * @generated from field: int32 total_notes = 1;
   */
  totalNotes: number;

  /**
   * @generated from field: int32 total_notes_this_month = 2;
   */
  totalNotesThisMonth: number;

  /**
   * @generated from field: int32 total_patients = 3;
   */
  totalPatients: number;

  /**
   * @generated from field: int32 total_patients_this_month = 4;
   */
  totalPatientsThisMonth: number;

  /**
   * @generated from field: int32 total_nurses = 5;
   */
  totalNurses: number;

  /**
   * @generated from field: int32 total_nurses_this_month = 6;
   */
  totalNursesThisMonth: number;

  /**
   * @generated from field: int32 total_admins = 7;
   */
  totalAdmins: number;

  /**
   * @generated from field: int32 total_admins_this_month = 8;
   */
  totalAdminsThisMonth: number;

  constructor(data?: PartialMessage<GetCompanyStatsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyStatsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyStatsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyStatsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyStatsResponse;

  static equals(a: GetCompanyStatsResponse | PlainMessage<GetCompanyStatsResponse> | undefined, b: GetCompanyStatsResponse | PlainMessage<GetCompanyStatsResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyBillingRequest
 */
export declare class GetCompanyBillingRequest extends Message<GetCompanyBillingRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  constructor(data?: PartialMessage<GetCompanyBillingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyBillingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyBillingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyBillingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyBillingRequest;

  static equals(a: GetCompanyBillingRequest | PlainMessage<GetCompanyBillingRequest> | undefined, b: GetCompanyBillingRequest | PlainMessage<GetCompanyBillingRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetCompanyBillingResponse
 */
export declare class GetCompanyBillingResponse extends Message<GetCompanyBillingResponse> {
  /**
   * @generated from field: company.v1.CompanyBilling billing = 1;
   */
  billing?: CompanyBilling;

  constructor(data?: PartialMessage<GetCompanyBillingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetCompanyBillingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCompanyBillingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCompanyBillingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCompanyBillingResponse;

  static equals(a: GetCompanyBillingResponse | PlainMessage<GetCompanyBillingResponse> | undefined, b: GetCompanyBillingResponse | PlainMessage<GetCompanyBillingResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetEstimatedSubscriptionCostRequest
 */
export declare class GetEstimatedSubscriptionCostRequest extends Message<GetEstimatedSubscriptionCostRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  constructor(data?: PartialMessage<GetEstimatedSubscriptionCostRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetEstimatedSubscriptionCostRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstimatedSubscriptionCostRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstimatedSubscriptionCostRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstimatedSubscriptionCostRequest;

  static equals(a: GetEstimatedSubscriptionCostRequest | PlainMessage<GetEstimatedSubscriptionCostRequest> | undefined, b: GetEstimatedSubscriptionCostRequest | PlainMessage<GetEstimatedSubscriptionCostRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.GetEstimatedSubscriptionCostResponse
 */
export declare class GetEstimatedSubscriptionCostResponse extends Message<GetEstimatedSubscriptionCostResponse> {
  /**
   * @generated from field: int32 estimated_cost = 1;
   */
  estimatedCost: number;

  /**
   * @generated from field: int32 total_seats = 2;
   */
  totalSeats: number;

  /**
   * @generated from field: int32 seats_to_remove = 3;
   */
  seatsToRemove: number;

  constructor(data?: PartialMessage<GetEstimatedSubscriptionCostResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.GetEstimatedSubscriptionCostResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstimatedSubscriptionCostResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstimatedSubscriptionCostResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstimatedSubscriptionCostResponse;

  static equals(a: GetEstimatedSubscriptionCostResponse | PlainMessage<GetEstimatedSubscriptionCostResponse> | undefined, b: GetEstimatedSubscriptionCostResponse | PlainMessage<GetEstimatedSubscriptionCostResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.PromoteAdminRequest
 */
export declare class PromoteAdminRequest extends Message<PromoteAdminRequest> {
  /**
   * @generated from field: string company_id = 1;
   */
  companyId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string token = 3;
   */
  token: string;

  constructor(data?: PartialMessage<PromoteAdminRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.PromoteAdminRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PromoteAdminRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PromoteAdminRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PromoteAdminRequest;

  static equals(a: PromoteAdminRequest | PlainMessage<PromoteAdminRequest> | undefined, b: PromoteAdminRequest | PlainMessage<PromoteAdminRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.DemoteAdminRequest
 */
export declare class DemoteAdminRequest extends Message<DemoteAdminRequest> {
  /**
   * @generated from field: string company_id = 1;
   */
  companyId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string token = 3;
   */
  token: string;

  constructor(data?: PartialMessage<DemoteAdminRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.DemoteAdminRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DemoteAdminRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DemoteAdminRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DemoteAdminRequest;

  static equals(a: DemoteAdminRequest | PlainMessage<DemoteAdminRequest> | undefined, b: DemoteAdminRequest | PlainMessage<DemoteAdminRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateCheckoutSessionRequest
 */
export declare class CreateCheckoutSessionRequest extends Message<CreateCheckoutSessionRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  constructor(data?: PartialMessage<CreateCheckoutSessionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateCheckoutSessionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCheckoutSessionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCheckoutSessionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCheckoutSessionRequest;

  static equals(a: CreateCheckoutSessionRequest | PlainMessage<CreateCheckoutSessionRequest> | undefined, b: CreateCheckoutSessionRequest | PlainMessage<CreateCheckoutSessionRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateCheckoutSessionResponse
 */
export declare class CreateCheckoutSessionResponse extends Message<CreateCheckoutSessionResponse> {
  /**
   * @generated from field: string checkout_url = 1;
   */
  checkoutUrl: string;

  constructor(data?: PartialMessage<CreateCheckoutSessionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateCheckoutSessionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCheckoutSessionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCheckoutSessionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCheckoutSessionResponse;

  static equals(a: CreateCheckoutSessionResponse | PlainMessage<CreateCheckoutSessionResponse> | undefined, b: CreateCheckoutSessionResponse | PlainMessage<CreateCheckoutSessionResponse> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateBillingPortalSessionRequest
 */
export declare class CreateBillingPortalSessionRequest extends Message<CreateBillingPortalSessionRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  constructor(data?: PartialMessage<CreateBillingPortalSessionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateBillingPortalSessionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBillingPortalSessionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBillingPortalSessionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBillingPortalSessionRequest;

  static equals(a: CreateBillingPortalSessionRequest | PlainMessage<CreateBillingPortalSessionRequest> | undefined, b: CreateBillingPortalSessionRequest | PlainMessage<CreateBillingPortalSessionRequest> | undefined): boolean;
}

/**
 * @generated from message company.v1.CreateBillingPortalSessionResponse
 */
export declare class CreateBillingPortalSessionResponse extends Message<CreateBillingPortalSessionResponse> {
  /**
   * @generated from field: string portal_url = 1;
   */
  portalUrl: string;

  constructor(data?: PartialMessage<CreateBillingPortalSessionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "company.v1.CreateBillingPortalSessionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBillingPortalSessionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBillingPortalSessionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBillingPortalSessionResponse;

  static equals(a: CreateBillingPortalSessionResponse | PlainMessage<CreateBillingPortalSessionResponse> | undefined, b: CreateBillingPortalSessionResponse | PlainMessage<CreateBillingPortalSessionResponse> | undefined): boolean;
}

