// @generated by protoc-gen-connect-es v1.4.0
// @generated from file note.proto (package note.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddChoiceToEventRequest, AddEventRequest, AddMethodToEventRequest, AddStepRequest, CreateNoteRequest, CreateNoteResponse, DeleteNoteRequest, GenerateNoteContentRequest, GetNoteRequest, GetNoteResponse, ListNotesRequest, ListNotesResponse, ListNurseNotesRequest, ListNurseNotesResponse, RemoveChoiceFromEventRequest, RemoveEventRequest, RemoveMethodFromEventRequest, RemoveStepRequest, UpdateChoiceInEventRequest, UpdateEventDescriptionRequest, UpdateNoteRequest } from "./note_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service note.v1.NoteTakingService
 */
export const NoteTakingService = {
  typeName: "note.v1.NoteTakingService",
  methods: {
    /**
     * @generated from rpc note.v1.NoteTakingService.CreateNote
     */
    createNote: {
      name: "CreateNote",
      I: CreateNoteRequest,
      O: CreateNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.UpdateNote
     */
    updateNote: {
      name: "UpdateNote",
      I: UpdateNoteRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.DeleteNote
     */
    deleteNote: {
      name: "DeleteNote",
      I: DeleteNoteRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.GetNote
     */
    getNote: {
      name: "GetNote",
      I: GetNoteRequest,
      O: GetNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.GenerateNoteContent
     */
    generateNoteContent: {
      name: "GenerateNoteContent",
      I: GenerateNoteContentRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.ListNotes
     */
    listNotes: {
      name: "ListNotes",
      I: ListNotesRequest,
      O: ListNotesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.ListNurseNotes
     */
    listNurseNotes: {
      name: "ListNurseNotes",
      I: ListNurseNotesRequest,
      O: ListNurseNotesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.AddEvent
     */
    addEvent: {
      name: "AddEvent",
      I: AddEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.RemoveEvent
     */
    removeEvent: {
      name: "RemoveEvent",
      I: RemoveEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.UpdateEventDescription
     */
    updateEventDescription: {
      name: "UpdateEventDescription",
      I: UpdateEventDescriptionRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.AddChoiceToEvent
     */
    addChoiceToEvent: {
      name: "AddChoiceToEvent",
      I: AddChoiceToEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.RemoveChoiceFromEvent
     */
    removeChoiceFromEvent: {
      name: "RemoveChoiceFromEvent",
      I: RemoveChoiceFromEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.UpdateChoiceInEvent
     */
    updateChoiceInEvent: {
      name: "UpdateChoiceInEvent",
      I: UpdateChoiceInEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.AddMethodToEvent
     */
    addMethodToEvent: {
      name: "AddMethodToEvent",
      I: AddMethodToEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.RemoveMethodFromEvent
     */
    removeMethodFromEvent: {
      name: "RemoveMethodFromEvent",
      I: RemoveMethodFromEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.AddStep
     */
    addStep: {
      name: "AddStep",
      I: AddStepRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc note.v1.NoteTakingService.RemoveStep
     */
    removeStep: {
      name: "RemoveStep",
      I: RemoveStepRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

