// @generated by protoc-gen-es v1.7.2
// @generated from file schemas.proto (package schemas, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { Extension } from "@bufbuild/protobuf";
import { EnumRules, StringRules } from "./buf/validate/validate_pb.js";

/**
 * @generated from extension: optional bool not_unspecified = 1000;
 */
export declare const not_unspecified: Extension<EnumRules, boolean>;

/**
 * @generated from extension: optional bool username = 1001;
 */
export declare const username: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool name = 1002;
 */
export declare const name: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool email = 1003;
 */
export declare const email: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool password = 1004;
 */
export declare const password: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool company_code = 1005;
 */
export declare const company_code: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool patient_name = 1006;
 */
export declare const patient_name: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool patient_additional_information = 1007;
 */
export declare const patient_additional_information: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool goal = 1008;
 */
export declare const goal: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool event_description = 1009;
 */
export declare const event_description: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool choice = 1010;
 */
export declare const choice: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool behavior_description = 1011;
 */
export declare const behavior_description: Extension<StringRules, boolean>;

/**
 * @generated from extension: optional bool note_additional_information = 1012;
 */
export declare const note_additional_information: Extension<StringRules, boolean>;

