// @generated by protoc-gen-es v1.7.2
// @generated from file session.proto (package session.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, proto3, Timestamp } from "@bufbuild/protobuf";
import { User } from "./user_pb.js";

/**
 * @generated from enum session.v1.RefreshState
 */
export const RefreshState = proto3.makeEnum(
  "session.v1.RefreshState",
  [
    {no: 0, name: "UnspecifiedRefreshState"},
    {no: 1, name: "RequiresPassword"},
    {no: 2, name: "RefreshedSuccessfully"},
  ],
);

/**
 * @generated from message session.v1.Session
 */
export const Session = proto3.makeMessageType(
  "session.v1.Session",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "expires_at", kind: "message", T: Timestamp },
    { no: 5, name: "mfa_verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message session.v1.SignUpRequest
 */
export const SignUpRequest = proto3.makeMessageType(
  "session.v1.SignUpRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "company_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.SignUpResponse
 */
export const SignUpResponse = proto3.makeMessageType(
  "session.v1.SignUpResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "session", kind: "message", T: Session },
  ],
);

/**
 * @generated from message session.v1.SignInRequest
 */
export const SignInRequest = proto3.makeMessageType(
  "session.v1.SignInRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.SignInResponse
 */
export const SignInResponse = proto3.makeMessageType(
  "session.v1.SignInResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "session", kind: "message", T: Session },
  ],
);

/**
 * @generated from message session.v1.SignOutRequest
 */
export const SignOutRequest = proto3.makeMessageType(
  "session.v1.SignOutRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
    { no: 3, name: "ignore_active_state", kind: "message", T: Empty, opt: true },
    { no: 4, name: "ignore_mfa", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message session.v1.RefreshSessionRequest
 */
export const RefreshSessionRequest = proto3.makeMessageType(
  "session.v1.RefreshSessionRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "ignore_active_state", kind: "message", T: Empty, opt: true },
    { no: 4, name: "ignore_status", kind: "message", T: Empty, opt: true },
    { no: 5, name: "ignore_mfa", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message session.v1.RefreshSessionResponse
 */
export const RefreshSessionResponse = proto3.makeMessageType(
  "session.v1.RefreshSessionResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "session", kind: "message", T: Session },
    { no: 3, name: "state", kind: "enum", T: proto3.getEnumType(RefreshState) },
  ],
);

/**
 * @generated from message session.v1.InitiateMFARequest
 */
export const InitiateMFARequest = proto3.makeMessageType(
  "session.v1.InitiateMFARequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ignore_mfa", kind: "message", T: Empty, opt: true },
    { no: 6, name: "ignore_status", kind: "message", T: Empty, opt: true },
    { no: 7, name: "ignore_active_state", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message session.v1.InitiateMFAResponse
 */
export const InitiateMFAResponse = proto3.makeMessageType(
  "session.v1.InitiateMFAResponse",
  () => [
    { no: 1, name: "masked_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.ResendMFACodeRequest
 */
export const ResendMFACodeRequest = proto3.makeMessageType(
  "session.v1.ResendMFACodeRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ignore_mfa", kind: "message", T: Empty, opt: true },
    { no: 6, name: "ignore_status", kind: "message", T: Empty, opt: true },
    { no: 7, name: "ignore_active_state", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message session.v1.ResendMFACodeResponse
 */
export const ResendMFACodeResponse = proto3.makeMessageType(
  "session.v1.ResendMFACodeResponse",
  () => [
    { no: 1, name: "masked_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.VerifyMFARequest
 */
export const VerifyMFARequest = proto3.makeMessageType(
  "session.v1.VerifyMFARequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "mfa_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ignore_mfa", kind: "message", T: Empty, opt: true },
    { no: 6, name: "ignore_status", kind: "message", T: Empty, opt: true },
    { no: 7, name: "ignore_active_state", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message session.v1.InitiateResetPasswordRequest
 */
export const InitiateResetPasswordRequest = proto3.makeMessageType(
  "session.v1.InitiateResetPasswordRequest",
  () => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.InitiateResetPasswordResponse
 */
export const InitiateResetPasswordResponse = proto3.makeMessageType(
  "session.v1.InitiateResetPasswordResponse",
  () => [
    { no: 1, name: "masked_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "challenge_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.VerifyResetPasswordRequest
 */
export const VerifyResetPasswordRequest = proto3.makeMessageType(
  "session.v1.VerifyResetPasswordRequest",
  () => [
    { no: 1, name: "challenge_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.VerifyResetPasswordResponse
 */
export const VerifyResetPasswordResponse = proto3.makeMessageType(
  "session.v1.VerifyResetPasswordResponse",
  () => [
    { no: 1, name: "reset_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message session.v1.ForgotUsernameRequest
 */
export const ForgotUsernameRequest = proto3.makeMessageType(
  "session.v1.ForgotUsernameRequest",
  () => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

