// @generated by protoc-gen-es v1.7.2
// @generated from file session.proto (package session.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Empty, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { User } from "./user_pb.js";

/**
 * @generated from enum session.v1.RefreshState
 */
export declare enum RefreshState {
  /**
   * @generated from enum value: UnspecifiedRefreshState = 0;
   */
  UnspecifiedRefreshState = 0,

  /**
   * @generated from enum value: RequiresPassword = 1;
   */
  RequiresPassword = 1,

  /**
   * @generated from enum value: RefreshedSuccessfully = 2;
   */
  RefreshedSuccessfully = 2,
}

/**
 * @generated from message session.v1.Session
 */
export declare class Session extends Message<Session> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: bool mfa_verified = 5;
   */
  mfaVerified: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Session>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.Session";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Session;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Session;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Session;

  static equals(a: Session | PlainMessage<Session> | undefined, b: Session | PlainMessage<Session> | undefined): boolean;
}

/**
 * @generated from message session.v1.SignUpRequest
 */
export declare class SignUpRequest extends Message<SignUpRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: string company_id = 5;
   */
  companyId: string;

  constructor(data?: PartialMessage<SignUpRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.SignUpRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignUpRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignUpRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignUpRequest;

  static equals(a: SignUpRequest | PlainMessage<SignUpRequest> | undefined, b: SignUpRequest | PlainMessage<SignUpRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.SignUpResponse
 */
export declare class SignUpResponse extends Message<SignUpResponse> {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: session.v1.Session session = 2;
   */
  session?: Session;

  constructor(data?: PartialMessage<SignUpResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.SignUpResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignUpResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignUpResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignUpResponse;

  static equals(a: SignUpResponse | PlainMessage<SignUpResponse> | undefined, b: SignUpResponse | PlainMessage<SignUpResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.SignInRequest
 */
export declare class SignInRequest extends Message<SignInRequest> {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  constructor(data?: PartialMessage<SignInRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.SignInRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignInRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignInRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignInRequest;

  static equals(a: SignInRequest | PlainMessage<SignInRequest> | undefined, b: SignInRequest | PlainMessage<SignInRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.SignInResponse
 */
export declare class SignInResponse extends Message<SignInResponse> {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: session.v1.Session session = 2;
   */
  session?: Session;

  constructor(data?: PartialMessage<SignInResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.SignInResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignInResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignInResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignInResponse;

  static equals(a: SignInResponse | PlainMessage<SignInResponse> | undefined, b: SignInResponse | PlainMessage<SignInResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.SignOutRequest
 */
export declare class SignOutRequest extends Message<SignOutRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_status = 2;
   */
  ignoreStatus?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_active_state = 3;
   */
  ignoreActiveState?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_mfa = 4;
   */
  ignoreMfa?: Empty;

  constructor(data?: PartialMessage<SignOutRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.SignOutRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignOutRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignOutRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignOutRequest;

  static equals(a: SignOutRequest | PlainMessage<SignOutRequest> | undefined, b: SignOutRequest | PlainMessage<SignOutRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.RefreshSessionRequest
 */
export declare class RefreshSessionRequest extends Message<RefreshSessionRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * optional argument, if passed and verified will revive an inactive session
   *
   * @generated from field: optional string password = 2;
   */
  password?: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_active_state = 3;
   */
  ignoreActiveState?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_status = 4;
   */
  ignoreStatus?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_mfa = 5;
   */
  ignoreMfa?: Empty;

  constructor(data?: PartialMessage<RefreshSessionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.RefreshSessionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshSessionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshSessionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshSessionRequest;

  static equals(a: RefreshSessionRequest | PlainMessage<RefreshSessionRequest> | undefined, b: RefreshSessionRequest | PlainMessage<RefreshSessionRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.RefreshSessionResponse
 */
export declare class RefreshSessionResponse extends Message<RefreshSessionResponse> {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: session.v1.Session session = 2;
   */
  session?: Session;

  /**
   * @generated from field: session.v1.RefreshState state = 3;
   */
  state: RefreshState;

  constructor(data?: PartialMessage<RefreshSessionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.RefreshSessionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshSessionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshSessionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshSessionResponse;

  static equals(a: RefreshSessionResponse | PlainMessage<RefreshSessionResponse> | undefined, b: RefreshSessionResponse | PlainMessage<RefreshSessionResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.InitiateMFARequest
 */
export declare class InitiateMFARequest extends Message<InitiateMFARequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_mfa = 5;
   */
  ignoreMfa?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_status = 6;
   */
  ignoreStatus?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_active_state = 7;
   */
  ignoreActiveState?: Empty;

  constructor(data?: PartialMessage<InitiateMFARequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.InitiateMFARequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitiateMFARequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitiateMFARequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitiateMFARequest;

  static equals(a: InitiateMFARequest | PlainMessage<InitiateMFARequest> | undefined, b: InitiateMFARequest | PlainMessage<InitiateMFARequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.InitiateMFAResponse
 */
export declare class InitiateMFAResponse extends Message<InitiateMFAResponse> {
  /**
   * @generated from field: string masked_email = 1;
   */
  maskedEmail: string;

  constructor(data?: PartialMessage<InitiateMFAResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.InitiateMFAResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitiateMFAResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitiateMFAResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitiateMFAResponse;

  static equals(a: InitiateMFAResponse | PlainMessage<InitiateMFAResponse> | undefined, b: InitiateMFAResponse | PlainMessage<InitiateMFAResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.ResendMFACodeRequest
 */
export declare class ResendMFACodeRequest extends Message<ResendMFACodeRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_mfa = 5;
   */
  ignoreMfa?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_status = 6;
   */
  ignoreStatus?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_active_state = 7;
   */
  ignoreActiveState?: Empty;

  constructor(data?: PartialMessage<ResendMFACodeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.ResendMFACodeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResendMFACodeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResendMFACodeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResendMFACodeRequest;

  static equals(a: ResendMFACodeRequest | PlainMessage<ResendMFACodeRequest> | undefined, b: ResendMFACodeRequest | PlainMessage<ResendMFACodeRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.ResendMFACodeResponse
 */
export declare class ResendMFACodeResponse extends Message<ResendMFACodeResponse> {
  /**
   * @generated from field: string masked_email = 1;
   */
  maskedEmail: string;

  constructor(data?: PartialMessage<ResendMFACodeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.ResendMFACodeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResendMFACodeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResendMFACodeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResendMFACodeResponse;

  static equals(a: ResendMFACodeResponse | PlainMessage<ResendMFACodeResponse> | undefined, b: ResendMFACodeResponse | PlainMessage<ResendMFACodeResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.VerifyMFARequest
 */
export declare class VerifyMFARequest extends Message<VerifyMFARequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string mfa_code = 2;
   */
  mfaCode: string;

  /**
   * hacky way to target this rpc with interceptor
   *
   * @generated from field: optional google.protobuf.Empty ignore_mfa = 5;
   */
  ignoreMfa?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_status = 6;
   */
  ignoreStatus?: Empty;

  /**
   * @generated from field: optional google.protobuf.Empty ignore_active_state = 7;
   */
  ignoreActiveState?: Empty;

  constructor(data?: PartialMessage<VerifyMFARequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.VerifyMFARequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMFARequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMFARequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMFARequest;

  static equals(a: VerifyMFARequest | PlainMessage<VerifyMFARequest> | undefined, b: VerifyMFARequest | PlainMessage<VerifyMFARequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.InitiateResetPasswordRequest
 */
export declare class InitiateResetPasswordRequest extends Message<InitiateResetPasswordRequest> {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  constructor(data?: PartialMessage<InitiateResetPasswordRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.InitiateResetPasswordRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitiateResetPasswordRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitiateResetPasswordRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitiateResetPasswordRequest;

  static equals(a: InitiateResetPasswordRequest | PlainMessage<InitiateResetPasswordRequest> | undefined, b: InitiateResetPasswordRequest | PlainMessage<InitiateResetPasswordRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.InitiateResetPasswordResponse
 */
export declare class InitiateResetPasswordResponse extends Message<InitiateResetPasswordResponse> {
  /**
   * @generated from field: string masked_email = 1;
   */
  maskedEmail: string;

  /**
   * @generated from field: string challenge_id = 2;
   */
  challengeId: string;

  constructor(data?: PartialMessage<InitiateResetPasswordResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.InitiateResetPasswordResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitiateResetPasswordResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitiateResetPasswordResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitiateResetPasswordResponse;

  static equals(a: InitiateResetPasswordResponse | PlainMessage<InitiateResetPasswordResponse> | undefined, b: InitiateResetPasswordResponse | PlainMessage<InitiateResetPasswordResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.VerifyResetPasswordRequest
 */
export declare class VerifyResetPasswordRequest extends Message<VerifyResetPasswordRequest> {
  /**
   * @generated from field: string challenge_id = 1;
   */
  challengeId: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  constructor(data?: PartialMessage<VerifyResetPasswordRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.VerifyResetPasswordRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyResetPasswordRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyResetPasswordRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyResetPasswordRequest;

  static equals(a: VerifyResetPasswordRequest | PlainMessage<VerifyResetPasswordRequest> | undefined, b: VerifyResetPasswordRequest | PlainMessage<VerifyResetPasswordRequest> | undefined): boolean;
}

/**
 * @generated from message session.v1.VerifyResetPasswordResponse
 */
export declare class VerifyResetPasswordResponse extends Message<VerifyResetPasswordResponse> {
  /**
   * @generated from field: string reset_token = 1;
   */
  resetToken: string;

  constructor(data?: PartialMessage<VerifyResetPasswordResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.VerifyResetPasswordResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyResetPasswordResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyResetPasswordResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyResetPasswordResponse;

  static equals(a: VerifyResetPasswordResponse | PlainMessage<VerifyResetPasswordResponse> | undefined, b: VerifyResetPasswordResponse | PlainMessage<VerifyResetPasswordResponse> | undefined): boolean;
}

/**
 * @generated from message session.v1.ForgotUsernameRequest
 */
export declare class ForgotUsernameRequest extends Message<ForgotUsernameRequest> {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  constructor(data?: PartialMessage<ForgotUsernameRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "session.v1.ForgotUsernameRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ForgotUsernameRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ForgotUsernameRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ForgotUsernameRequest;

  static equals(a: ForgotUsernameRequest | PlainMessage<ForgotUsernameRequest> | undefined, b: ForgotUsernameRequest | PlainMessage<ForgotUsernameRequest> | undefined): boolean;
}

