// @generated by protoc-gen-connect-es v1.4.0
// @generated from file session.proto (package session.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ForgotUsernameRequest, InitiateMFARequest, InitiateMFAResponse, InitiateResetPasswordRequest, InitiateResetPasswordResponse, RefreshSessionRequest, RefreshSessionResponse, ResendMFACodeRequest, ResendMFACodeResponse, SignInRequest, SignInResponse, SignOutRequest, SignUpRequest, SignUpResponse, VerifyMFARequest, VerifyResetPasswordRequest, VerifyResetPasswordResponse } from "./session_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service session.v1.AuthenticationService
 */
export declare const AuthenticationService: {
  readonly typeName: "session.v1.AuthenticationService",
  readonly methods: {
    /**
     * @generated from rpc session.v1.AuthenticationService.SignUp
     */
    readonly signUp: {
      readonly name: "SignUp",
      readonly I: typeof SignUpRequest,
      readonly O: typeof SignUpResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.SignIn
     */
    readonly signIn: {
      readonly name: "SignIn",
      readonly I: typeof SignInRequest,
      readonly O: typeof SignInResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.SignOut
     */
    readonly signOut: {
      readonly name: "SignOut",
      readonly I: typeof SignOutRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.RefreshSession
     */
    readonly refreshSession: {
      readonly name: "RefreshSession",
      readonly I: typeof RefreshSessionRequest,
      readonly O: typeof RefreshSessionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.InitiateMFA
     */
    readonly initiateMFA: {
      readonly name: "InitiateMFA",
      readonly I: typeof InitiateMFARequest,
      readonly O: typeof InitiateMFAResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.ResendMFACode
     */
    readonly resendMFACode: {
      readonly name: "ResendMFACode",
      readonly I: typeof ResendMFACodeRequest,
      readonly O: typeof ResendMFACodeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.VerifyMFA
     */
    readonly verifyMFA: {
      readonly name: "VerifyMFA",
      readonly I: typeof VerifyMFARequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.InitiateResetPassword
     */
    readonly initiateResetPassword: {
      readonly name: "InitiateResetPassword",
      readonly I: typeof InitiateResetPasswordRequest,
      readonly O: typeof InitiateResetPasswordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.VerifyResetPassword
     */
    readonly verifyResetPassword: {
      readonly name: "VerifyResetPassword",
      readonly I: typeof VerifyResetPasswordRequest,
      readonly O: typeof VerifyResetPasswordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.ForgotUsername
     */
    readonly forgotUsername: {
      readonly name: "ForgotUsername",
      readonly I: typeof ForgotUsernameRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

