// @generated by protoc-gen-connect-es v1.4.0
// @generated from file session.proto (package session.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ForgotUsernameRequest, InitiateMFARequest, InitiateMFAResponse, InitiateResetPasswordRequest, InitiateResetPasswordResponse, RefreshSessionRequest, RefreshSessionResponse, ResendMFACodeRequest, ResendMFACodeResponse, SignInRequest, SignInResponse, SignOutRequest, SignUpRequest, SignUpResponse, VerifyMFARequest, VerifyResetPasswordRequest, VerifyResetPasswordResponse } from "./session_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service session.v1.AuthenticationService
 */
export const AuthenticationService = {
  typeName: "session.v1.AuthenticationService",
  methods: {
    /**
     * @generated from rpc session.v1.AuthenticationService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.SignOut
     */
    signOut: {
      name: "SignOut",
      I: SignOutRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.RefreshSession
     */
    refreshSession: {
      name: "RefreshSession",
      I: RefreshSessionRequest,
      O: RefreshSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.InitiateMFA
     */
    initiateMFA: {
      name: "InitiateMFA",
      I: InitiateMFARequest,
      O: InitiateMFAResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.ResendMFACode
     */
    resendMFACode: {
      name: "ResendMFACode",
      I: ResendMFACodeRequest,
      O: ResendMFACodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.VerifyMFA
     */
    verifyMFA: {
      name: "VerifyMFA",
      I: VerifyMFARequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.InitiateResetPassword
     */
    initiateResetPassword: {
      name: "InitiateResetPassword",
      I: InitiateResetPasswordRequest,
      O: InitiateResetPasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.VerifyResetPassword
     */
    verifyResetPassword: {
      name: "VerifyResetPassword",
      I: VerifyResetPasswordRequest,
      O: VerifyResetPasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc session.v1.AuthenticationService.ForgotUsername
     */
    forgotUsername: {
      name: "ForgotUsername",
      I: ForgotUsernameRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

