// @generated by protoc-gen-connect-es v1.4.0
// @generated from file user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApproveNurseRequest, ChangeUserPasswordRequest, ChangeUserPasswordWResetTokenRequest, DeleteUserRequest, GetUserRequest, GetUserResponse, GetUsersStatsRequest, GetUsersStatsResponse, ListPendingNursesRequest, ListPendingNursesResponse, ListUsersRequest, ListUsersResponse, RejectNurseRequest, SearchUsersRequest, SearchUsersResponse, UpdateUserRequest } from "./user_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserManagementService
 */
export const UserManagementService = {
  typeName: "user.v1.UserManagementService",
  methods: {
    /**
     * @generated from rpc user.v1.UserManagementService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ChangeUserPassword
     */
    changeUserPassword: {
      name: "ChangeUserPassword",
      I: ChangeUserPasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ChangeUserPasswordWResetToken
     */
    changeUserPasswordWResetToken: {
      name: "ChangeUserPasswordWResetToken",
      I: ChangeUserPasswordWResetTokenRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.GetUsersStats
     */
    getUsersStats: {
      name: "GetUsersStats",
      I: GetUsersStatsRequest,
      O: GetUsersStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.SearchUsers
     */
    searchUsers: {
      name: "SearchUsers",
      I: SearchUsersRequest,
      O: SearchUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ListPendingNurses
     */
    listPendingNurses: {
      name: "ListPendingNurses",
      I: ListPendingNursesRequest,
      O: ListPendingNursesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ApproveNurse
     */
    approveNurse: {
      name: "ApproveNurse",
      I: ApproveNurseRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.RejectNurse
     */
    rejectNurse: {
      name: "RejectNurse",
      I: RejectNurseRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

