// @generated by protoc-gen-connect-es v1.4.0
// @generated from file user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApproveNurseRequest, ChangeUserPasswordRequest, ChangeUserPasswordWResetTokenRequest, DeleteUserRequest, GetUserRequest, GetUserResponse, GetUsersStatsRequest, GetUsersStatsResponse, ListPendingNursesRequest, ListPendingNursesResponse, ListUsersRequest, ListUsersResponse, RejectNurseRequest, SearchUsersRequest, SearchUsersResponse, UpdateUserRequest } from "./user_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserManagementService
 */
export declare const UserManagementService: {
  readonly typeName: "user.v1.UserManagementService",
  readonly methods: {
    /**
     * @generated from rpc user.v1.UserManagementService.GetUser
     */
    readonly getUser: {
      readonly name: "GetUser",
      readonly I: typeof GetUserRequest,
      readonly O: typeof GetUserResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.UpdateUser
     */
    readonly updateUser: {
      readonly name: "UpdateUser",
      readonly I: typeof UpdateUserRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ChangeUserPassword
     */
    readonly changeUserPassword: {
      readonly name: "ChangeUserPassword",
      readonly I: typeof ChangeUserPasswordRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ChangeUserPasswordWResetToken
     */
    readonly changeUserPasswordWResetToken: {
      readonly name: "ChangeUserPasswordWResetToken",
      readonly I: typeof ChangeUserPasswordWResetTokenRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.DeleteUser
     */
    readonly deleteUser: {
      readonly name: "DeleteUser",
      readonly I: typeof DeleteUserRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ListUsers
     */
    readonly listUsers: {
      readonly name: "ListUsers",
      readonly I: typeof ListUsersRequest,
      readonly O: typeof ListUsersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.GetUsersStats
     */
    readonly getUsersStats: {
      readonly name: "GetUsersStats",
      readonly I: typeof GetUsersStatsRequest,
      readonly O: typeof GetUsersStatsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.SearchUsers
     */
    readonly searchUsers: {
      readonly name: "SearchUsers",
      readonly I: typeof SearchUsersRequest,
      readonly O: typeof SearchUsersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ListPendingNurses
     */
    readonly listPendingNurses: {
      readonly name: "ListPendingNurses",
      readonly I: typeof ListPendingNursesRequest,
      readonly O: typeof ListPendingNursesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.ApproveNurse
     */
    readonly approveNurse: {
      readonly name: "ApproveNurse",
      readonly I: typeof ApproveNurseRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserManagementService.RejectNurse
     */
    readonly rejectNurse: {
      readonly name: "RejectNurse",
      readonly I: typeof RejectNurseRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

