// @generated by protoc-gen-es v1.7.2
// @generated from file user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum user.v1.Status
 */
export const Status = proto3.makeEnum(
  "user.v1.Status",
  [
    {no: 0, name: "UnspecifiedStatus"},
    {no: 1, name: "Pending"},
    {no: 2, name: "Accepted"},
    {no: 3, name: "Rejected"},
  ],
);

/**
 * @generated from enum user.v1.Role
 */
export const Role = proto3.makeEnum(
  "user.v1.Role",
  [
    {no: 0, name: "UnspecifiedRole"},
    {no: 1, name: "SuperAdmin"},
    {no: 2, name: "Admin"},
    {no: 3, name: "Nurse"},
  ],
);

/**
 * @generated from message user.v1.User
 */
export const User = proto3.makeMessageType(
  "user.v1.User",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "email_verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(Status) },
    { no: 7, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
    { no: 8, name: "company_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "is_licensed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "created_at", kind: "message", T: Timestamp },
    { no: 12, name: "updated_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message user.v1.GetUserRequest
 */
export const GetUserRequest = proto3.makeMessageType(
  "user.v1.GetUserRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.PartialPatient
 */
export const PartialPatient = proto3.makeMessageType(
  "user.v1.PartialPatient",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.GetUserResponse
 */
export const GetUserResponse = proto3.makeMessageType(
  "user.v1.GetUserResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "patients", kind: "message", T: PartialPatient, repeated: true },
  ],
);

/**
 * @generated from message user.v1.UpdateUserRequest
 */
export const UpdateUserRequest = proto3.makeMessageType(
  "user.v1.UpdateUserRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.ChangeUserPasswordRequest
 */
export const ChangeUserPasswordRequest = proto3.makeMessageType(
  "user.v1.ChangeUserPasswordRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "current_password", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "new_password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.ChangeUserPasswordWResetTokenRequest
 */
export const ChangeUserPasswordWResetTokenRequest = proto3.makeMessageType(
  "user.v1.ChangeUserPasswordWResetTokenRequest",
  () => [
    { no: 1, name: "reset_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "new_password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.DeleteUserRequest
 */
export const DeleteUserRequest = proto3.makeMessageType(
  "user.v1.DeleteUserRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.ListUsersRequest
 */
export const ListUsersRequest = proto3.makeMessageType(
  "user.v1.ListUsersRequest",
  () => [
    { no: 1, name: "full_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(Status), opt: true },
    { no: 4, name: "role", kind: "enum", T: proto3.getEnumType(Role), opt: true },
    { no: 5, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 7, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.ListUsersResponse
 */
export const ListUsersResponse = proto3.makeMessageType(
  "user.v1.ListUsersResponse",
  () => [
    { no: 1, name: "users", kind: "message", T: User, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "next_page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message user.v1.SearchUsersRequest
 */
export const SearchUsersRequest = proto3.makeMessageType(
  "user.v1.SearchUsersRequest",
  () => [
    { no: 1, name: "full_name_query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.SearchedUser
 */
export const SearchedUser = proto3.makeMessageType(
  "user.v1.SearchedUser",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "full_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
  ],
);

/**
 * @generated from message user.v1.SearchUsersResponse
 */
export const SearchUsersResponse = proto3.makeMessageType(
  "user.v1.SearchUsersResponse",
  () => [
    { no: 1, name: "users", kind: "message", T: SearchedUser, repeated: true },
  ],
);

/**
 * @generated from message user.v1.ListPendingNursesRequest
 */
export const ListPendingNursesRequest = proto3.makeMessageType(
  "user.v1.ListPendingNursesRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ignore_status", kind: "message", T: Empty, opt: true },
  ],
);

/**
 * @generated from message user.v1.ListPendingNursesResponse
 */
export const ListPendingNursesResponse = proto3.makeMessageType(
  "user.v1.ListPendingNursesResponse",
  () => [
    { no: 1, name: "nurses", kind: "message", T: User, repeated: true },
  ],
);

/**
 * @generated from message user.v1.ApproveNurseRequest
 */
export const ApproveNurseRequest = proto3.makeMessageType(
  "user.v1.ApproveNurseRequest",
  () => [
    { no: 1, name: "nurse_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message user.v1.RejectNurseRequest
 */
export const RejectNurseRequest = proto3.makeMessageType(
  "user.v1.RejectNurseRequest",
  () => [
    { no: 1, name: "nurse_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

